# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2024-09-07T15:49:53+00:00

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import BaseModel, Field


class Request(BaseModel):
    query: str = Field(..., title='Query')


class Response(BaseModel):
    text: str = Field(..., title='Text')


class ValidationError(BaseModel):
    loc: List[Union[str, int]] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class HTTPValidationError(BaseModel):
    detail: Optional[List[ValidationError]] = Field(None, title='Detail')
